[package]
name = "dead-agents-switch"
version = "0.1.0"
description = "Digital wills for the agent economy"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "dead_agents_switch"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"
